- name: Create HTML report on Windows
  hosts: windows
  gather_facts: yes
  tasks:

    - name: Create report directory
      ansible.windows.win_file:
        path: "{{ file_path }}"
        state: directory

    - name: Create HTML report file
      ansible.windows.win_template:
        src: report.j2
        dest: "{{ file_path }}\\windowspatch.html"

    - name: Copy CSS folder
      ansible.windows.win_copy:
        src: css
        dest: "{{ file_path }}\\css"

    - name: Copy logo
      ansible.windows.win_copy:
        src: webpage_logo.png
        dest: "{{ file_path }}\\webpage_logo.png"

    - name: Display link to Patch report
      ansible.builtin.debug:
        msg: "Open C:\\{{ file_path }}\\windowspatch.html on the Windows host"
